### ISSUE TITLE
실라버스 페이지 내용 확인 부타 

### ISSUE THREAD

**Issue by hyojaeKwon** [HyojaeKwon-GIST20/ICT-volunteer-page#9]
실라버스 hello java 

![캡처](https://user-images.githubusercontent.com/70756219/128007663-4c33731a-ef5e-4718-b450-16758cab16ba.PNG)

확인 바랍니다

@ChoiEungi

**Comment by ChoiEungi** [comment]
테스트 용으로 넣었음. 곧 변경 예정
